(eval-when (load eval)
  (MAPC 'ATTACHFEAT
  '((exercise run running zoomba taichi gym biking bike hike hiking)
   (walk walking)
   (garden gardening gardener lawn floral plant plants)
   (sew sewing knit knitting crochet)
   (water-related boat boating kayak kayaking canoeing swimming swim swimmer)
   (game games cards card scrabble)
   (theater movies show shows) 
   (music concert concerts singing)
   (read reading book)
   (book books)
   (sport sports volleyball basketball baseball)
   (golf golfing)
   (friend friends)
   (travel)
   (cook cooking)
   (volunteer volunteering)
   (grandchild grandchildren grandson granddaughter babysitting)
   (art artist)
   (dance dancing)  
   ))
;; (what are your hobbies ?)
;;	(hobbies)
;;		from-hobbies-input
;;			(0 my hobby is 0)
;;			gist-question:(3 what are 1 hobbies 0)

 (READRULES '*specific-answer-from-hobbies-input*
   '(1 (0 exercise 0) 
        2 ((my hobby is 2 \.)  (hobbies)) (0 :gist) 		
     1 (0 beach 0)
	    2 (0 walk 4 beach 0) 
          3 ((my hobby is walking on the beach \.)  (hobbies)) (0 :gist) 		
        2 (0) 
          3 ((my hobby is going to the beach \.)  (hobbies)) (0 :gist) 		
     1 (0 garden 0) 
        2 ((my hobby is gardening \.)  (hobbies)) (0 :gist) 		
     1 (0 sew 0) 
        2 ((my hobby is 2 \.)  (hobbies)) (0 :gist) 		
     1 (0 water-related 0) 
        2 ((my hobby is a kind of water sport \.)  (hobbies)) (0 :gist) 		
     1 (0 play game 0) 
        2 ((my hobby is playing 3 \.)  (hobbies)) (0 :gist) 		
     1 (0 theater 0) 
        2 ((my hobby is going to theater \.)  (hobbies)) (0 :gist) 		
     1 (0 music 0) 
        2 ((my hobby is 2 \.)  (hobbies)) (0 :gist) 		
     1 (0 sport 0) 
        2 ((my hobby is sports \.)  (hobbies)) (0 :gist) 		
     1 (0 golf 0) 
        2 ((my hobby is golf \.)  (hobbies)) (0 :gist) 		
     1 (0 read 0) 
        2 ((my hobby is reading \.)  (hobbies)) (0 :gist) 		
     1 (0 book clubs 0) 
        2 ((my hobby is reading \.)  (hobbies)) (0 :gist) 		
     1 (0 library 0) 
        2 ((my hobby is going to library \.)  (hobbies)) (0 :gist) 		
     1 (0 dance 0) 
        2 ((my hobby is dance \.)  (hobbies)) (0 :gist) 		
     1 (0 friend 0) 
        2 ((my hobby is being with friends \.)  (hobbies)) (0 :gist) 		
     1 (0 travel 0) 
        2 ((my hobby is traveling \.)  (hobbies)) (0 :gist) 		
     1 (0 cook 0) 
        2 ((my hobby is cooking \.)  (hobbies)) (0 :gist) 		
     1 (0 volunteer 0) 
        2 ((my hobby is volunteering \.)  (hobbies)) (0 :gist) 		
     1 (0 grandchild 0) 
        2 ((my hobby is being with my grandchildren \.)  (hobbies)) (0 :gist) 		
    ; 1 (0 art 0) 
    ;    2 ((my hobby is going to theater \.)  (hobbies)) (0 :gist) 		
     ))
       
       
 (READRULES '*thematic-answer-from-hobbies-input*
    '())

 (READRULES '*unbidden-answer-from-hobbies-input*
    '())
		
 (READRULES '*question-from-hobbies-input*
    '(1 (0 what 2 you 0)
        2 (what are your hobbies ?) (0 :gist)
      1 (0 how 2 you 0)
        2 (what are your hobbies ?) (0 :gist)
	  1 (0 wh_ 4 hobbies 0)
        2 (what are your hobbies ?) (0 :gist)
      ))

(READRULES '*reaction-to-hobbies-input*
   '(1 (0 exercise 0)
       2 (It\'s good to stay active\.) (100 :out)
     1 (0 beach 0)
       2 (You like going to the beach\, too\.) (100 :out)
     1 (0 gardening 0)
       2 (Gardening is a good hobby\. It\'s nice to be outdoors\.) (100 :out)
     1 (0 sew 0)
       2 (That\'s nice! It\'s a very practical hobby too\.) (100 :out)
     1 (0 water sport 0)
       2 (That sounds cool\. You can\'t go in the water for obvious reasons\, but it looks fun\.) (100 :out)
     1 (0 playing game 0)
       2 (3 sounds like a fun game \.) (100 :out)
     1 (0 theater 0)
       2 (That\'s nice\. You like the theater too \.) (100 :out)
     1 (0 music 0)
       2 (That\'s great! You like music too \.) (100 :out)
     1 (0 sports 0)
       2 (That sounds fun\. It\'s good to stay active\.) (100 :out)
     1 (0 golf 0)
       2 (That\'s great\. It\'s nice to spend time on the golf course\.) (100 :out)
     1 (0 reading 0)
       2 (Oh\, that\'s nice! You like reading too\.) (100 :out)
     1 (0 library 0)
       2 (You like going to the library\, too\. You can always find an interesting book to read\.) (100 :out)
     1 (0 dance 0)
       2 (Dancing is really fun! It\'s good to stay active\.) (100 :out)
     1 (0 friend 0)
       2 (It\'s nice to talk with friends\. It helps you stay positive\.) (100 :out)
     1 (0 traveling 0)
       2 (You like traveling\. It\'s fun to see new places\.) (100 :out)
     1 (0 cooking 0)
       2 (Cooking is really fun! You like trying out new recipes\.) (100 :out)
     1 (0 volunteering 0)
       2 (Volunteering is nice\. It\'s good to give back to the community\.) (100 :out)
     1 (0 grandchildren 0)
       2 (It\'s nice to be with family\. You have heard grandchildren are especially fun\.) (100 :out)
     1 (0 art 0)
       2 (Art is a cool hobby\. It\'s fun to be creative\.) (100 :out)
	))
); end of eval-when
