(eval-when (load eval)
 (MAPC 'ATTACHFEAT
  '((school university department)
    (bigger larger)
	(nature natural green scene scenary)
    (social-environment people community neighbourhood)
	(weather cold snow snows snowy winter)
	(urban-life streets)
	(much many)
	(culture art museum music)
	(nice good)
	(cuisine food foods restaurant restaurants eating dishes)
	(restaurant restaurants diner diners)
	(food foods garbage)
    ))

;; (what do you like better in Rochester ?)
;;	(like-better-in-Rochester)
;;		from-like-better-in-Rochester-input
;;			(What I like better in Rochester is 0)     
 
 (READRULES '*specific-answer-from-like-better-in-Rochester-input*
 '(1 (0 bigger 0) 
     2 ((What I like better in Rochester is that it is bigger \.)  (like-better-in-Rochester)) (0 :gist) 
   1 (0 more fun 0) 
     2 ((What I like better in Rochester is that there is more fun here \.)  (like-better-in-Rochester)) (0 :gist) 
   1 (0 I like social-environment 0) 
     2 ((What I like better in Rochester is 4 \.)  (like-better-in-Rochester)) (0 :gist) 
   1 (0 can be 0 alone 0) 
     2 ((What I like better in Rochester is that I can be alone \.)  (like-better-in-Rochester)) (0 :gist) 
   1 (0 school 0) 
     2 ((What I like better in Rochester is the school \.)  (like-better-in-Rochester)) (0 :gist) 
   1 (0 like 5 weather 0) 
     2 ((What I like better in Rochester is the weather \.)  (like-better-in-Rochester)) (0 :gist) 
   1 (0 like 5 nature 0) 
     2 ((What I like better in Rochester is the nature \.)  (like-better-in-Rochester)) (0 :gist) 
   1 (0 weather 2 nice 0)
     2 ((What I like better in Rochester is the weather \.) (like-better-in-rochester)) (0 :gist)
   1 (0 not 5 much 0)
	 2 ((no opinion about what I like better in Rochester \.) (like-better-in-rochester)) (0 :gist)
   1 (0 NEG 3 much 3 city 0)
	 2 ((no opinion about what I like better in Rochester \.) (like-better-in-rochester)) (0 :gist)
   1 (0 NEG 2 around 0)
	 2 ((no opinion about what I like better in Rochester \.) (like-better-in-rochester)) (0 :gist)
   1 (0 like 3 cuisine 0)
	 2 (0 restaurant 0)
	   3 ((What I like better in Rochester is restaurants \.) (like-better-in-rochester)) (0 :gist)
     2 (0 food 0)
	   3 ((What I like better in Rochester is foods \.) (like-better-in-rochester)) (0 :gist)   
   1 (0 cuisine 2 nice 0) 
	 2 (0 restaurant 0)
	   3 ((What I like better in Rochester is restaurants \.) (like-better-in-rochester)) (0 :gist)
     2 (0 food 0)
	   3 ((What I like better in Rochester is foods \.) (like-better-in-rochester)) (0 :gist)   
   1 (0 social-environment 0)
	 2 ((What I like better in Rochester is 2 \.) (like-better-in-rochester)) (0 :gist)
   1 (0 culture 0) 
	 2 ((What I like better in Rochester is 2 \.) (like-better-in-rochester)) (0 :gist)
   1 (0 urban-life 0) 
	 2 ((What I like better in Rochester is 2 \.) (like-better-in-rochester)) (0 :gist) 
	1 (0 NEG like anything 1 better 0) 
	 2 ((What I like better in Rochester is nothing \.) (like-better-in-rochester)) (0 :gist) 
	1 (0 like nothing 1 better 0) 
	 2 ((What I like better in Rochester is nothing \.) (like-better-in-rochester)) (0 :gist) 
	 ))
 
 (READRULES '*thematic-answer-from-like-better-in-Rochester-input*
    '())

 (READRULES '*unbidden-answer-from-like-better-in-Rochester-input*
	())

 (READRULES '*question-from-like-better-in-Rochester-input* 
    '(1 (0 what 0 you 0)
        2 (what do you like better in Rochester ?) (0 :gist)
      1 (0 what 2 like better in Rochester 0)
        2 (what do you like better in Rochester ?) (0 :gist)
      1 (0 how 0 you 0)
        2 (what do you like better in Rochester ?) (0 :gist)
    ))
 
 (READRULES '*reaction-to-like-better-in-Rochester-input*  
 '(1 (0 bigger 0) 
     2 (Yeah\, Rochester is a rather large city \.) 
	   (100 :out) 
   1 (0 social-environment 0)   ; social-environment people community neighbourhood
     2 (0 people 0) 
	   3 (You also found people very nice here \.) 
	     (100 :out) 
     2 (0) 
       3 (You also found the community nice here \.) 
	     (100 :out) 
   1 (0 more fun 0) 
     2 (That\'s cool that I have more fun here \.) 
	   (100 :out) 
   1 (0 can be alone 0) 
     2 (Yeah\, as a student I could find some times to be alone here \.) 
	   (100 :out) 
   1 (0 weather 0) 
     2 (Really? You love Rochester in Spring and Summer but it is cold in the rest of the year \.) 
	   (100 :out) 
   1 (0 nature 0) 
     2 (Yeah\, one can find incredibly beautiful nature around here \.) 
	   (100 :out) 
   1 (0 school 0) 
     2 (That\'s good that I like the school \.) 
	   (100 :out) 
   1 (0 no opinion 0) 
     2 (OK\, let\'s move on \.) 
	   (100 :out) 
   1 (0 cuisine 0)
     2 (0 foods 0)
       3 (You do like foods here too \.)	 
	   (100 :out) 
     2 (0 restaurants 0) 
	   3 (Yeah\, there are lots of great restaurants here \.)
	     (100 :out) 
   1 (0 culture 0)              ; culture art museum music 
     2 (0 music 0) 
	   3 (Yeah\, Rochester is well known for it\'s music schools \.) (100 :out)
     2 (0) 
	   3 (So I care about cultural activities \.)
	   (100 :out)	   
   1 (0 urban-life 0)           ; urban-life streets
     2 (Really? Interesting! \.) 
	   (100 :out) 
   1 (0 like 3 is nothing 0)           ; urban-life streets
     2 (So you do not like Rochester that much \.) 
	   (100 :out) 
   1 (0) 
     2 (Really? Interesting! \.) 
	   (100 :out) 
   )); end of *reaction-to-like-better-in-Rochester-input*

); end of eval-when

