(eval-when (load eval)
 (MAPC 'ATTACHFEAT
  '((popular-Cities North-Eastern-Cities Northern-Cities North-Western-Cities South-Western-Cities Southern-Cities Western-Cities) 
    (less-popular-Cities South-to-Rochester Central-Cities)
	(North-Eastern-Cities Boston Philadelphia Washington Baltimore)
	(Northern-Cities Chicago Indianapolis Columbus Detroit Cleveland)
	(North-Western-Cities Seattle)
	(South-Western-Cities Phoenix)
	(Southern-Cities Houston Dallas Austin Miami)
	(South-to-Rochester Atlanta Charlotte)
	(Central-Cities Memphis Denver Kansas)
    (popular-States California Florida Massachusetts Ohio Texas Pennsylvania Maryland Virginia Colorado Vermont)
    (stay staying)
	(Rochester here)
	(think thought)
	(Western-Cities LA Francisco)
	(think thought)
	(other-popular-places London Paris Italy Iceland)
    ))

;; (where would you live if money was not a concern ?)
;;	(ideal-place-to-live)
;;		from-ideal-place-to-live-input
;;			(If money was not an issue I would live in 1 0)
;;			gist-question:(where would you live 2 money 0)
 
 (READRULES '*specific-answer-from-ideal-place-to-live-input*
 '(1 (0 New York 0) 
        2 ((If money was not an issue I would live in 2 \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 Los Angeles 0) 
        2 ((If money was not an issue I would live in 2 3 \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 San Antonio 0) 
        2 ((If money was not an issue I would live in 2 3 \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 San Jose 0) 
        2 ((If money was not an issue I would live in 2 3 \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 San Diego 0) 
        2 ((If money was not an issue I would live in 2 3 \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 popular-Cities 0) 
        2 ((If money was not an issue I would live in 2 \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 popular-States 0) 
        2 ((If money was not an issue I would live in 2 \.)  (ideal-place-to-live)) (0 :gist) 		
   1 (0 other-popular-places 0) 
        2 ((If money was not an issue I would live in 2 \.)  (ideal-place-to-live)) (0 :gist) 		
   1 (0 less-popular-Cities 0) 
        2 ((If money was not an issue I would live in 2 \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 stay 2 Rochester 0) 
        2 ((If money was not an issue I would live in Rochester \.)  (ideal-place-to-live)) (0 :gist) 		
   1 (0 have NEG 0 think 0)
        2 ((I have not thought that if money was not an issue where I would live \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 NEG 0 know 0)
        2 ((I have not thought that if money was not an issue where I would live \.)  (ideal-place-to-live)) (0 :gist) 
   1 (0 have not given it 2 thought 0)
        2 ((I have not thought that if money was not an issue where I would live \.)  (ideal-place-to-live)) (0 :gist) 
	1 (0 3 0)
        2 ((Nothing found for if money was not an issue where I would live \.)  (ideal-place-to-live)) (0 :gist) 
	))
 
 (READRULES '*thematic-answer-from-ideal-place-to-live-input*
    '())

 (READRULES '*unbidden-answer-from-ideal-place-to-live-input*
	'())

 (READRULES '*question-from-ideal-place-to-live-input* 
    '(1 (0 what 0 you 0)
        2 (where would you live if money was not an issue ?) (0 :gist)
      1 (0 how 0 you 0)
        2 (where would you live if money was not an issue ?) (0 :gist)
	  1 (0 where would you live 0)
        2 (where would you live if money was not an issue ?) (0 :gist)	
     ))
 
 (READRULES '*reaction-to-ideal-place-to-live-input*  
 '(1 (0 have not thought 0)
      2 (You would live in a warm place near the water \.) 
        (100 :out)
    1 (0 I would live in 0)    
	  2 (0 New York City 0)
        3 (Many famous and rich people choose to live in New York City \.)
          (100 :out)
      2 (0 Los Angeles 0)
        3 (Many famous and rich people choose to live in Los Angeles \.)
          (100 :out)
      2 (0 San Antonio 0)
        3 (You haven\'t been in 2 3 but it looks like a nice place to live \.) 
          (100 :out)
      2 (0 San Jose 0)
        3 (You haven\'t been in 2 3 but it looks like a nice place to live \.) 
          (100 :out)
      2 (0 San Diego 0)
        3 (You haven\'t been in 2 3 but it looks like a nice place to live \.) 
          (100 :out)
	  2 (0 popular-Cities 0)
	    3 (0 Eastern-Cities 0)
		  4 (The weather is nice in the west coast \.) 
		    (100 :out)
		3 (0 Northern-Cities 0)
		  4 (You wouldn\'t live in such a cold city if you had enough money \.) 
		    (100 :out)
		3 (0 North-Western-Cities 0)
		  4 (You haven\'t been in 2 but it looks like a nice place to live \.)
		    (100 :out)
		3 (0 South-Western-Cities 0)
		  4 (Isn\'t there too hot in summer \? You wouldn\'t live in such a hot area \.)  
		    (100 :out)
		3 (0 Southern-Cities 0)
		  4 (0 Miami 0)
		    5 (That\'s the best place to spend time in winter. Many rich people have their own villa in Miami \.)  
		      (100 :out)
		  4 (0)
		    5 (Isn\'t there too hot during summer \? You wouldn\'t live in such a hot area \.)  
		      (100 :out)	 
		3 (0 Western-Cities 0)
		  4 (0 LA 0)
		    5 (Many famous and rich people choose to live in Los Angeles \.)
		      (100 :out)
		  4 (0 Francisco 0)
            5 (You haven\'t been in San Francisco but it looks like a nice place to live \.) 
		      (100 :out)		  
	  2 (0 popular-States 0)
	    3 (0 California 0)
		  4 (Many rich people choose to live in California \.)
		    (100 :out)
		3 (0 Florida 0)
		  4 (Many rich people choose to live in Florida \.) 
		    (100 :out)
		3 (0 Massachusetts 0)
		  4 (Really? But there is even colder than Rochester \.)  
		    (100 :out)
		3 (0 Texas 0)
		  4 (Isn\'t there too hot in summer \? You wouldn\'t live in such a hot area \.)
		    (100 :out)
		3 (0 Colorado 0)
		  4 (It looks like a nice place to live \.)
		    (100 :out)
		3 (0 Vermont 0)
		  4 (It looks like a nice place to live \.)
            (100 :out)		  
		3 (0)  ;; Ohio Maryland Pennsylvania Virginia
		  4 (Really \? you haven\'t been there yet \.) 
		    (100 :out)
	1 (I want to stay here 0)
       2 (Seriously \? looks like you like Rochester a lot \.) 
        (100 :out)
	1 (0 3 0)
       2 (That\'s a great choice!) 
        (100 :out)	
    )); end of *reaction-to-ideal-place-to-live-input*

); end of eval-when

