(eval-when (load eval)
 (MAPC 'ATTACHFEAT
  '((house detached)
	(patio balcony terrace backyard)
	(game)
	(water seaside riverside shore lake river)
	(luxary)
	(modern)
	(country village)
	(instruments piano guitar drum drums)
	(antique old ancestral)
	(suburb suburban commuting)
	(windows)
	(think thought)
    ))

;; (what would your dream home be like ?)
;;	(dream-home)
;;		from-dream-home-input
;;			(My dream home is 0) 
;;			gist-question: (what 2 dream home 0)
      
 
 (READRULES '*specific-answer-from-dream-home-input*
 '(1 (0 patio 0) 
        2 ((My dream home is a home with patio \.)  (dream-home)) (0 :gist) 
   1 (0 game 0) 
        2 ((My dream home is a home with a game room \.)  (dream-home)) (0 :gist) 
   1 (0 water 0) 
        2 ((My dream home is a home near water \.)  (dream-home)) (0 :gist) 
   1 (0 luxary 0) 
        2 ((My dream home is a luxary home \.)  (dream-home)) (0 :gist) 
   1 (0 modern 0) 
        2 ((My dream home is a modern home \.)  (dream-home)) (0 :gist) 
   1 (0 country 0) 
        2 ((My dream home is a country house \.)  (dream-home)) (0 :gist) 
   1 (0 instruments 0) 
        2 ((My dream home is a home with instruments in it \.)  (dream-home)) (0 :gist) 
   1 (0 big TV 0) 
        2 ((My dream home is a home with a big TV in it \.)  (dream-home)) (0 :gist) 
   1 (0 antique 0) 
        2 ((My dream home is an antique home \.)  (dream-home)) (0 :gist) 
   1 (0 suburb 0) 
        2 ((My dream home is a suburban home \.)  (dream-home)) (0 :gist) 
   1 (0 big windows 0) 
        2 ((My dream home is a home with big windows \.)  (dream-home)) (0 :gist) 
   1 (0 house 0) 
        2 ((My dream home is a house \.)  (dream-home)) (0 :gist) 
   1 (0 NEG know 0) 
        2 ((I have no idea how my dream home is \.)  (dream-home)) (0 :gist) 
   1 (0 don\'t know 0) 
        2 ((I have no idea how my dream home is \.)  (dream-home)) (0 :gist) 
   1 (0 NEG idea 0) 
        2 ((I have no idea how my dream home is \.)  (dream-home)) (0 :gist) 
   1 (0 don\'t have 2 idea 0) 
        2 ((I have no idea how my dream home is \.)  (dream-home)) (0 :gist) 
   
   1 (0 3 0) 
        2 ((Nothing found for how my dream home is \.)  (dream-home)) (0 :gist) 
    ))
 
 (READRULES '*thematic-answer-from-dream-home-input*
    '())

 (READRULES '*unbidden-answer-from-dream-home-input*
	'())

 (READRULES '*question-from-dream-home-input* 
    '(1 (0 what 0 you 0)
        2 (what would your dream home be like ?) (0 :gist)
      1 (0 how 0 you 0)
        2 (what would your dream home be like ?) (0 :gist)
     ))
 
 (READRULES '*reaction-to-dream-home-input*  
 '(1 (0 patio 0) 
     2 (You love to sit and relax in patio \.) 
	   (100 :out)
   1 (0 game 0) 
     2 (Having a game room is an exciting idea \.) 
	   (100 :out)
   1 (0 water 0) 
     2 (Living near the water would definitely be fantastic \.) 
	   (100 :out) 
   1 (0 luxary 0) 
     2 (That\'s nice to live in such a home \.) 
	   (100 :out)
   1 (0 modern 0) 
     2 (You would prefer a modern home too \.) 
	   (100 :out)
   1 (0 country 0) 
     2 (You love to live in a peace and quiet country home \.) 
	   (100 :out)
   1 (0 instruments 0) 
     2 (You love living by the water \.) 
	   (100 :out)
   1 (0 big tv 0) 
     2 (Living in a luxary home would cost a lot \.) 
	   (100 :out) 
   1 (0 antique 0)
     2 (OK\.) 
	   (100 :out)
   1 (0 suburban 0)
     2 (You love to live in a peace and quiet suburban home \.)
	   (100 :out)
   1 (0 big windows 0)
     2 (You also like a house with big windows \.) 
	   (100 :out)
   1 (0 house 0)
     2 (You also prefer houses to apartments \.) 
	   (100 :out)
   1 (0 3 0)
     2 (Cool \!) 
	   (100 :out)   
)); end of *reaction-to-dream-home-input*

); end of eval-when

