(eval-when (load eval)
  (MAPC 'ATTACHFEAT
  '((snow snowy snowing)
     (sun sunny)
    (rain rainy)
	(cold freezing)
	(moderate pleasant mild)
    (lot lots)
	(season-names fall spring summer winter)
	(like liked loved love)
  ))
    
;; (how did you like the weather in your hometown ?)
;;	(hometown-weather)
;;		from-hometown-weather-input
;;			(0 the weather in my hometown is 0)
;;			gist-question:(3 how 2 like the weather 2 hometown 0)

 (READRULES '*specific-answer-from-hometown-weather-input*
   '(1 (0 hot 0)
       2 (0 NEG like 1 hot 0) 
         3 ((I do not like the weather to be hot \.)  (hometown-weather)) (0 :gist) 		
       2 (0 don\'t like 1 hot 0) 
         3 ((I do not like the weather to be hot \.)  (hometown-weather)) (0 :gist) 		
       2 (0 didn\'t like 1 hot 0) 
         3 ((I do not like the weather to be hot \.)  (hometown-weather)) (0 :gist) 		
       2 (0 not 1 hot 0)
	     3 ((the weather in my hometown is not too hot \.)  (hometown-weather)) (0 :gist) 		
	   2 (0)
	     3 ((probably the weather in my hometown is hot \.)  (hometown-weather)) (0 :gist) 		
	 1 (0 snow 0)
	   2 (0 NEG like 2 snow 0) 
         3 ((I do not the weather to be snowy \.)  (hometown-weather)) (0 :gist) 		
       2 (0 don\'t like 2 snow 0) 
         3 ((I do not like the weather to be snowy \.)  (hometown-weather)) (0 :gist) 		
       2 (0 do not like 2 snow 0) 
         3 ((I do not like the weather to be snowy \.)  (hometown-weather)) (0 :gist) 		
       2 (0 didn\'t like 2 snow 0) 
         3 ((I do not like the weather to be snowy \.)  (hometown-weather)) (0 :gist) 		       
       2 (0) 
         3 ((probably the weather in my hometown is snowy \.)  (hometown-weather)) (0 :gist) 		       
	 1 (0 I like 2 seasons 0) 
        2 ((I like the weather in all the seasons \.)  (hometown-weather)) (0 :gist) 		
     1 (0 I like 2 change 2 seasons 0) 
        2 ((I like the weather in all the seasons \.)  (hometown-weather)) (0 :gist) 		
     1 (0 sun 0)
	    2 (0 I like 2 sun 0) 
          3 ((I like the weather to be sunny \.)  (hometown-weather)) (0 :gist) 		
        2 (0) 
          3 ((probably the weather in my hometown is sunny \.)  (hometown-weather)) (0 :gist) 		
	 1 (0 rain 0)
	   2 (0 we had 2 lot 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we have 2 lot 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we\'ve 2 lot 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it was 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
	   2 (0 it is 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it\'s 1 rain 0) 
         3 ((the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
       2 (0) 
         3 ((probably the weather in my hometown is rainy \.)  (hometown-weather)) (0 :gist) 		
     1 (0 cold 0)
	   2 (0 we had 2 lot 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we have 2 lot 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we\'ve 2 lot 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it got 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
	   2 (0 it was 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
	   2 (0 it is 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 weather was 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
	   2 (0 weather is 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it\'s 1 cold 0) 
         3 ((the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
       2 (0)
	     3 ((probably the weather in my hometown is cold \.)  (hometown-weather)) (0 :gist) 		
	 1 (0 moderate 0)
	   2 (0 we had 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we have 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 we\'ve got 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it is 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0 it was 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
	   2 (0 it\'s got 3 moderate 0) 
         3 ((the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
       2 (0)
	     3 ((probably the weather in my hometown is moderate \.)  (hometown-weather)) (0 :gist) 		
	 1 (0 same as rochester 3  0) 
        2 ((the weather in my hometown is same as rochester \.)  (hometown-weather)) (0 :gist) 		
     1 (0 same as here 3  0) 
        2 ((the weather in my hometown is same as rochester \.)  (hometown-weather)) (0 :gist) 		 
     1 (0 season-names 0) 
	   2(0 I like 2 season-names 0) 
         3 ((I like the weather in all the seasons \.)  (hometown-weather)) (0 :gist) 		
       2(0 season-names 0) 
         3 ((I talked about how seasons and the weather in my hometown is \.)  (hometown-weather)) (0 :gist) 		
     
   ))
       
       
 (READRULES '*thematic-answer-from-hometown-weather-input*
    '())

 (READRULES '*unbidden-answer-from-hometown-weather-input*
    '())
		
 (READRULES '*question-from-hometown-weather-input*
    '())

(READRULES '*reaction-to-hometown-weather-input*
   '(1 (0 NEG like 0 hot 0)
  2 (If I am not a fan of hot weather\, then I must like Rochester!) (100 :out)
1 (0 hot 0)
  2 (You lived in Texas for a long time\, so you are used to hot weather\. Rochester is a big change for you\.) (100 :out)
1 (0 NEG like 0 snowy 0)
  2 (If I do not like snow\, then it should be hard for me in Rochester!) (100 :out)
1 (0 snowy 0)
  2 (Oh\, you love snow\. that\'s really fun\. ) (100 :out)
1 (0 rainy 0)
  2 (You love rain\, especially the weather after a heavy rain\.) (100 :out)
1 (0 cold 0)
  2 (Oh\, in your opinion cold weather is better than hot\. Just be sure to stay warm when I am there!) (100 :out)
1 (0 moderate 0)
  2 (That\'s nice\.) (100 :out)
1 (0 same as rochester 0)
  2 (So I must be used to this kind of weather\.) (100 :out)
1 (0 all the seasons 0)
  2 (That\'s really great to experience all seasons\.) (100 :out)
1 (0)
  2 (Okay\.) (100 :out)
	))
); end of eval-when
